changes in login and register activity....
Deakyu/fitness-app pull request #3
Opened 2018-06-26 22:15 UTC by JesusArmandoM

2018-06-27 17:31 UTC, itzcoatl90 commented on app/src/main/java/com/example/deakyu/fitnessapp/LoginActivity.kt
> +        return password.length > 4
nice catch

2018-06-27 17:34 UTC, itzcoatl90 commented on app/src/main/java/com/example/deakyu/fitnessapp/RegisterActivity.kt
> +        weight.error = null
Are we putting a null value to variables?   Is this a good procedure? does code line 33 and 32 comes by default created by Android?

2018-06-27 17:36 UTC, itzcoatl90 commented on app/src/main/java/com/example/deakyu/fitnessapp/RegisterActivity.kt
> +        if (TextUtils.isEmpty(passwordStr) && !isPasswordValid(passwordStr)) {
Are we doing the same here and in LoginActivity? can we reuse the code?

2018-06-27 17:38 UTC, itzcoatl90 commented on app/src/main/java/com/example/deakyu/fitnessapp/RegisterActivity.kt
>      private fun isPasswordValid(password: String): Boolean {
Same here, we are using the same lines of code coming from LoginActivity.... unless the Regular Expressions we are going to use are different, we should not do that

2018-06-27 17:45 UTC, itzcoatl90 requested changes
Please review

2018-06-28 01:57 UTC, JesusArmandoM commented on app/src/main/java/com/example/deakyu/fitnessapp/RegisterActivity.kt
>      private fun isPasswordValid(password: String): Boolean {
Yes we have to change this in order to not duplicate functionality, we can achieve this in the task that we need to do in order to authenticate to the user (with firebase) even more than that we need to create our viewmodel related with this activity (and change the layour to achieve mvvm)

2018-06-28 01:58 UTC, JesusArmandoM commented on app/src/main/java/com/example/deakyu/fitnessapp/RegisterActivity.kt
> +        if (TextUtils.isEmpty(passwordStr) && !isPasswordValid(passwordStr)) {
Yes we have to change this in order to not duplicate functionality, we can achieve this in the task that we need to do in order to authenticate to the user (with firebase) even more than that we need to create our viewmodel related with this activity (and change the layour to achieve mvvm)

2018-06-28 02:00 UTC, JesusArmandoM commented on app/src/main/java/com/example/deakyu/fitnessapp/RegisterActivity.kt
> +        weight.error = null
when you create a new project with kotlin and select the login (predesigned project), you can find this approach.

2018-06-28 02:40 UTC, Deakyu approved these changes

2018-06-28 02:49 UTC, itzcoatl90 commented on app/src/main/java/com/example/deakyu/fitnessapp/RegisterActivity.kt
> +        weight.error = null
ok

2018-06-28 02:53 UTC, itzcoatl90 commented on app/src/main/java/com/example/deakyu/fitnessapp/RegisterActivity.kt
> +        if (TextUtils.isEmpty(passwordStr) && !isPasswordValid(passwordStr)) {
What about imaging that this was still a pull request and that it did not proceed.... can we do that now? making this methods to be in an kind of login utility and not saving this to other ticket? please

2018-06-28 02:53 UTC, itzcoatl90 commented on app/src/main/java/com/example/deakyu/fitnessapp/RegisterActivity.kt
>      private fun isPasswordValid(password: String): Boolean {
What about imaging that this was still a pull request and that it did not proceed.... can we do that now? making this methods to be in an kind of login utility and not saving this to other ticket? please

2018-06-28 02:58 UTC, merged